### PR TITLE
Loc update

### PR DESCRIPTION
**Pull request by NotaInutilis**
- FR loc up to date with EN
- Replaced undefined "\ue016" unicode character by the black diamond "\u25c6" that actually shows up in the app.

BTW I still have no idea how to properly use the localization python stuff. Fed it some -r and -w and it spat some errors to my face.

`PS D:\Développement\Traductions\aio-switch-updater> python .\localizer.py -rD:\Développement\Traductions\aio-switch-updater\resources\i18n\en-US\menus.json -w D:\Développement\Traductions\aio-switch-updater\resources\i18n\fr\menus.json
Traceback (most recent call last):
  File "D:\Développement\Traductions\aio-switch-updater\localizer.py", line 77, in <module>
    loc = Localizer(args.reference, args.working)
  File "D:\Développement\Traductions\aio-switch-updater\localizer.py", line 29, in __init__
    self.init_dicts()
  File "D:\Développement\Traductions\aio-switch-updater\localizer.py", line 33, in init_dicts
    self.reference_dict = json.load(reference_file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 13820: character maps to <undefined>`

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
Thank you!
For the localizer thing, are you not missing a space after -r?
python .\localizer.py -rD:\Développement\Traductions\aio-switch-updater\resources\i18n\en-US\menus.json -w D:\Développement\Traductions\aio-switch-updater\resources\i18n\fr\menus.json
>-rD:\Déve

**Comment by NotaInutilis** [comment]
Oh boy I was hoping it was just a typo but, even with a space, 
Capture d’écran 2022-03-10 141203
the error's still here.

**Comment by HamletDuFromage** [comment]
can you try by changing 
```
        with open(self.reference_path) as reference_file:
            self.reference_dict = json.load(reference_file)
        with open(self.working_path) as working_file:
            self.working_dict = json.load(working_file)
```
by
```
        with open(self.reference_path, encoding="utf8") as reference_file:
            self.reference_dict = json.load(reference_file)
        with open(self.working_path, encoding="utf8") as working_file:
            self.working_dict = json.load(working_file)
```

at https://github.com/HamletDuFromage/aio-switch-updater/blob/master/localizer.py#L32-L35

**Comment by NotaInutilis** [comment]
ÇA MARCHE ! \o/
The line display is pretty weird though.
`Translation for key: [old_cheats_found] was not found.  
Type in the translation in the field below.  
Type "_exit" to save & quit and "_skip" to go to skip to the next key.  
<<< ←[96mCheat codes matching BID(s) [ {}] exist.←[0m`
That "←[96m" and "←[0m" does not seem to be part of the line so I'm not sure what it means.

**Comment by HamletDuFromage** [comment]
It's just some (linux specific?) terminal thing to make the line bold and cyan so that it is easier to see
You can change `return f"{self.OKCYAN}{message}{self.ENDC}"` to `return message` to get rid of it in github.com/HamletDuFromage/aio-switch-updater/blob/master/localizer.py#L18-L19

**Pull request merged**
