### PR TITLE
Add a multi-language option and Chinese option 

### PR DESCRIPTION
**Pull request by tiansongyu**
Hey, I I added a multi-language option successfully and I added lots of code ,you can merge it after you clean the code. I leave some annotation in code ,so you can reference them.

there are some work you should do , 
1. You know the app use borealis lib ,but it doesn't support Chinese Special language characters acquiescently. We need to change the  [lib code.](https://github.com/tiansongyu/borealis/blob/8a0afc8179e2f2bf990ce9f8fb4733ad461b004e/library/lib/application.cpp#L247) You should add this code in the lib ,and fork  the borealis and use it 
2. Two choices that setting up the language. 
   one way is automatically to set .
   another way is create a file to save the language 
I choose the second one , any way , your app ,you choose the fit way
3. fix my code. emmmmm , may be there are some bugs(I don't know .  I tested it though) haha ,any way ,I think My work is worth.
4. Your code is clear for me to read ,but you can set up some dir and put the .cpp files into it
5. last but not least ,have a good day !   :D

Finally I don't know how to change the submodule (borealis) We should not use the current version. You know we should hack it 
Add Chinese fonts or other fonts. it's your work now .

everyone can supply the translation file to add a new language support (after you fix some code to add a new language option).

cheer~

### CODE REVIEW

**Comment by tiansongyu** [comment]
I  know how to change the submodule now .
I use the submodule from [tiansongyu borealis repositories ](https://github.com/tiansongyu/borealis) 
 you can change the submodule , now the Chinese Font is fine

**Comment by HamletDuFromage** [comment]
Looks good, thanks a lot!

**Comment by tiansongyu** [comment]
:D   ᕕ😆ᕗ my pleasure

**Comment by tiansongyu** [comment]
LOL borealis lib is amazing . it even have this [this function](https://github.com/HamletDuFromage/borealis/blob/b81a39f73b98aa61919b251521ba1297157a3cf7/library/lib/i18n.cpp#L159) that I always use and Other useful functions. I maybe will use this lib to create my app :D. I have learned a lot .

**Pull request merged**
