### PR TITLE
jp fix sorry

### PR DESCRIPTION
**Pull request by yyoossk**

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
Sorry, I made a few commit... could you try fixing the conflicts? If you can't, I'll do it myself
Thanks again for the translation!

**Comment by yyoossk** [comment]
sorry
I'm a beginner so I don't know how to do it
May I do it for you?
sorry for my poor english

**Comment by HamletDuFromage** [comment]
Don't worry, I'll take care of it

**Comment by HamletDuFromage** [comment]
I implemented the changes in this commit https://github.com/HamletDuFromage/aio-switch-updater/commit/154f9793e3b37870d2dd4bcf575fadb92eb8be49

I didn't know how to resolve conflicts from your pull request and properly merge it so I made the changes by hand and credited you in the commit. I hope it's ok!

**Comment by yyoossk** [comment]
thx!

**Pull request closed without merging**
