### PR TITLE
japanese fix and update

### PR DESCRIPTION
**Pull request by yyoossk**

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
Hey, thank you. Could you pull the latest changes of my repo and do a pull request that I can merge? If you do that, don't forget to backup your translation files so you don't lose the changes you just did

**Comment by yyoossk** [comment]
ok
thx！

**Comment by yyoossk** [comment]
sorry 
I don't know how to do it
sorry for my poor english

**Comment by HamletDuFromage** [comment]
So you can either do what's written here, https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream/39628366

or just delete your repo and fork it again.

If you can't, I'll add it manually but it's better the other way

**Comment by yyoossk** [comment]
ok
done

**Pull request closed without merging**
