### PR TITLE
add a time remaining indication

### PR DESCRIPTION
**Pull request by PoloNX**

### CODE REVIEW

**Comment by BeckysFootSlave** [comment]
Really good!
Implemented and tested it here! 
Maybe some formatting on how it is shown because sometimes it is in the loading bar!

I like it!!!

**Comment by PoloNX** [comment]
> But please think about a description on PRs = easier for the Dev!

Sorry I’m not very good in English. I thought it was good

**Comment by BeckysFootSlave** [comment]
All fine!

Just saying that it is easier instead of = No description provided

Glad that I "fall" over this and saw it!
Looking at "files changed" helped me to understand it, and I can't even code!

In case of how it is shown in Updater:
Would using "\n" in the menus json help?

  "worker": {
    "of": "of",
    "remaining": "Time remaining"
  }

**Comment by PoloNX** [comment]
I will do a commit juste to put the text 30 px over

**Comment by BeckysFootSlave** [comment]
Just a question if that is also possible:

`std::string labelText = fmt::format("({:.1f} MB {} {:.1f} MB - {:.1f} MB/s) - {}: ", 
                                        fileSizeCurrentMB, "menus/worker/of"_i18n, fileSizeFinalMB, speedMB, "menus/worker/remaining"_i18n);

    if (hours > 0)
        labelText += fmt::format("{}h ", "menus/worker/hours"_i18n);
    if (minutes > 0)
        labelText += fmt::format("{}m ", "menus/worker/minutes"_i18n);

    labelText += fmt::format("{}s", "menus/worker/seconds"_i18n);

    return labelText;`

and in the menus.json:

`  "worker": {
    "of": "of",
    "remaining": "Time remaining",
    "hours": "hours",
    "minutes": "minutes",
    "seconds": "seconds"
  }`

Forgive me if it is stupid! (like I said I CAN'T code :( )

But now you could translate that also :)

**Comment by PoloNX** [comment]
It's a good idea. I can't test now but here is the new commit

**Comment by PoloNX** [comment]
Here is the nro : 
[aio-switch-updater.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/11769933/aio-switch-updater.zip)

**Comment by BeckysFootSlave** [comment]
> Here is the nro : [aio-switch-updater.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/11769933/aio-switch-updater.zip)

Thank you, but prefer source because I compile it myself 😉

**Comment by PoloNX** [comment]
Ahah thanks. It works ?

**Comment by PoloNX** [comment]
Yes I see thanks for the feedback

**Comment by BeckysFootSlave** [comment]
Made a screenshot for you (German)

2023061620205500-CC47F0DEC75C1FD3B1F95FA9F9D57667

**Comment by BeckysFootSlave** [comment]
@PoloNX
Ist it possible to get it also for extracting?
Would be nice!

Greetings from Germany

**Comment by PoloNX** [comment]
I don't know how to do it

**Pull request merged**
