### PR TITLE
added the theme deletion, not just a message which say "there is a theme"

### PR DESCRIPTION
**Pull request by PoloNX**
I added one state in the firmware download which delete the theme if the user have one theme and want to delete it. 
If you have some question about it just ask me.

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
I don't love the idea of this app being used to delete files. I think the scope is already more than wide enough as it is

**Comment by PoloNX** [comment]
It's a choice for the user, it's not obligated

**Comment by HamletDuFromage** [comment]
I'm aware, but this is still added complexity to do something that should be done by NX theme installer. Even though aio is quite bloated in many aspects, I still want to adhere to the Unix philosophy as much as possible.

**Comment by PoloNX** [comment]
I understand. good job for the dev of the app

**Pull request closed without merging**
