### PR TITLE
Create brls.json

### PR DESCRIPTION
**Pull request by pedruhb**
Brazillian Portuguese translation part 1

### CODE REVIEW

**Comment by PHB2001** [comment]
sorry for creating two, I never used that ...

**Comment by HamletDuFromage** [comment]
Hey, thanks for the PR!
Would you say Portuguese and Brazilian Portuguese are close enough that your translation works for both locales? I thought it would be, but I'm reading online that there are some differences I was not aware of

**Comment by PHB2001** [comment]
the pleasure is mine, pt-pt and pt-br is totally understandable, what changes the most is the voice and the accent, the writing not much ...

**Comment by HamletDuFromage** [comment]
Great! I'll merge it and make a release as soon as I can :)

**Comment by pedruhb** [comment]
:) nice

**Pull request merged**
