### PR TITLE
Download firmwares from Mega

### PR DESCRIPTION
**Pull request by aedalzotto**
This PR allows downloading firmwares from Mega.
As discussed in #48, the first approach used cpr and cryptopp.
Due to packaging problems (and performance?), this PR still uses pure curl and libnx AES implementation.

Minimal changes were made to the code base.
To fetch Mega links, it tries to get the "firmwares_mega" key in nxlinks.json.
In its absence, it falls back to "firmwares" key in nxlinks.json.
This assures the link compatibility with users running previous aio-switch-updater versions is not broken.

The download speed is still not optimal, but way better (2-3x) than archive.org.
I have tried increasing the buffer size before writing to file with no success, so it does not seem related to fwrite slowness.
It needs further investigation, but maybe it's the aes128CtrCrypt slowing the download.

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
Thank you for the PR! 
I'm not really able to merge it at the moment, can't test it etc. 

I don't think adding a specific key is needed, with the previous versions of AIO, even when given a mega link it should say that it's not an archive and exit gracefully. And even if it doesn't, a crash isn't the end of the world, users should always update to the latest version. 

For the md5sum, I don't think it is necessary either. Daybreak checks the integrity of the sysupdate anyways. Unless I'm mistaken, there is no way it would install a broken update.

**Comment by aedalzotto** [comment]
I've removed the specific mega key, and now it should used the former 'firmwares' key.
The downloading works normally with both archive.org and mega.nz links.
The only problem is with older versions, but I agree that everyone should be running the latest version.

**Comment by aedalzotto** [comment]
As for md5sum, I strongly suspect that Daybreak verifies **validity** (i.e., whether the update file format is correct) and not **integrity** (i.e., the downloaded update is exactly what was uploaded to the server).

**Comment by HamletDuFromage** [comment]
> As for md5sum, I strongly suspect that Daybreak verifies **validity** (i.e., whether the update file format is correct) and not **integrity** (i.e., the downloaded update is exactly what was uploaded to the server).

Does it matter though? Because whether the archive is broken or the firmware tampered with, daybreak wouldn't install it, right?

**Pull request merged**
