### PR TITLE
Improve and add Spanish to the version 2.17.1

### PR DESCRIPTION
**Pull request by Armi-Heavy**
Hello! I have improved the translation and added the new functions to Spanish since there was a lot without translating, it would be incredible to be able to add this translation to the repository, thank you very much in advance ;)

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
Hey, thank you! Definitely interested in improving the localization so this is much appreciated. 
I see you changed `es` to `es-ES` though, I think that's a breaking change (see https://switchbrew.org/wiki/Settings_services#LanguageCode). Was the app not in Spanish for you already already? I don't think the Switch differentiates Spanish from Spain from South American Spanish

**Comment by Armi-Heavy** [comment]
Uppsss sorry, my fault, normally in IT "es-ES" is for Spanish from Spain, but I understand that in the switch just "es" is enough

**Comment by Armi-Heavy** [comment]
I have made the changes so that it does not cause problems

**Comment by HamletDuFromage** [comment]
Sweet! Thank you :)

**Pull request merged**
